apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCX5A9pYMDj6jRz+RW29tCGcC/IanN1WJPnVBj37jYz4QKsmBEuD2j5XtSJa1e58ZBmaEEtZWGCIK+HXo5hqiWCCYl47/GRWPfa3mbbhS9MG2Jkk3FJvpEoC4Y07CyUYa2X6eIIzE4zwDG6Si3aNuomSsobbVEiUZZkDvutJA0l2V87SRSBFpmzEa8vLTN6FmClRBVr/MOzBqYqeKFhM18F/GaKuD+manRKtL8m+ZNMdpbGEuzOMXzYAeufnu1qoFpPyrslWY8W5a5PMd9fYfTvXhW2I9/jc87EKK32j32wTSftgrCgR4P5ncGs+1+bzqLcQP6x+6bIq1X1kqCXB4rXCkfwaH9kyRY1ZW3CKeTYvKUTsuKzLCo2Gf5gI+nB9B0TKfBtiXiCaQb2oJO3R1mbUL2K2P3srgfvNresI1354mEuynZn6Rtz87hPdvrUl3Xvx+Ca3fb8AjfsKwV7dS59yCNWaRVCBBViw+xBjsDvfLaPtJ7VyrS9n+56gg89FP9XVynkCYX9IQ+4xLBuocMNr92mvmh8GRPYVM01KAQ+pPN50/TvlYE9SckqoVN/Ed0SZ4a+wAwkm6m1GBGCtjQFCG56f/x+43cqJSrJr6q5V4qZZ2YYIYC7bqmeQ6usgABIfX2Kr8XJTCQgKbbcBgOtttI/4e+HBdfMrTbO3K029RMzOa/G/y4wgnl5WjQpNLBKTviAItFxnsVWOj1waQHXc1ta6c0PvnRsxjMsIKH5pK1XkyP86Y73
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

